sec13_62
Section 13 vid62
- Custom Clientside Validation Involving Data Repositories

So if you wanna create a custom validation with your own business, you could put an @ annotation to the interface, for example
if you named the interface UniqueValue then it would become @UniqueValue

jadi jika kamu lihat annotation validation bawaan, nanti method di dalam interface custom kita memiliki method define yg sama, yaitu:
String message() default "Unique Constraint violated";
Class<?>[] groups() default{};
Class<?extends Payload>[] payload() default{};

One thing you should know, noted this.

Jadi ketika class validator yg di include kan pada interface validation di jalankan pada saat submit form, maka di background dia di jalankan 2x, yg pertama pada saat validasi field, lalu yg kedua pada saat input, maka secara default, ketika input data, data yg di annotation-kan validator custom tadi tidak memiliki nilai, karena wired yg digunakan pada validator classnya tidak dijalankan kembali seperti pada saat pertama validasi di awal. error yg akan terjadi adalah:
java.lang.NullPointerException: Cannot invoke "com.wilson.pma.dao.EmployeeRepository.findByEmail(String)" because "this.empRepo" is null,
untuk mengatasi hal ini, kita dapat men-setting di properties yaitu:
spring.jpa.properties.javax.persistence.validation.mode=none  (thats what we called client-side validation)